SET IDENTITY_INSERT [dbo].[Ingredients] ON
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (1, 9000, N'tomato-sauce', 30, N'../images/ingredients/tomato-sauce.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (2, 9000, N'smoked', 30, N'../images/ingredients/smoked.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (4, 9000, N'hot', 30, N'../images/ingredients/hot.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (5, 13500, N'bacon', 50, N'../images/ingredients/bacon.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (6, 12000, N'ham', 50, N'../images/ingredients/ham.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (7, 15000, N'sausage', 50, N'../images/ingredients/sausage.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (8, 6000, N'tomato', 50, N'../images/ingredients/tomato.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (9, 10500, N'champignon', 50, N'../images/ingredients/champignons.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (10, 6000, N'cucumber', 20, N'../images/ingredients/cucumber.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (11, 4500, N'black olives', 15, N'../images/ingredients/olives.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (12, 3000, N'olives', 10, N'../images/ingredients/spanish-olives.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (13, 18000, N'shrimp', 40, N'../images/ingredients/shrimp.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (16, 15000, N'squid', 50, N'../../images/ingredients/squid.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (17, 28500, N'mocarella', 100, N'../images/ingredients/mocarella.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (18, 30000, N'bri', 100, N'../images/ingredients/bri.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (19, 25000, N'feta', 100, N'../images/ingredients/feta.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (20, 28000, N'cheder', 100, N'../images/ingredients/cheder.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (21, 32000, N'holland', 100, N'../images/ingredients/holland.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (22, 300, N'garlic', 5, N'../images/ingredients/garlic.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (23, 900, N'lemon', 20, N'../images/ingredients/lemon.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (25, 900, N'greenery', 5, N'../images/ingredients/greenery.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (26, 4500, N'chilli', 10, N'../images/ingredients/chilli.jpg')
INSERT INTO [dbo].[Ingredients] ([Id], [Price], [Name], [Weight], [Photo]) VALUES (27, 7500, N'bulgarian peppe', 30, N'../images/ingredients/bulgarian-pepper.jpg')
SET IDENTITY_INSERT [dbo].[Ingredients] OFF
